# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.AlterField(
            model_name='category',
            name='cag_image',
            field=models.ImageField(upload_to='banner'),
        ),
    ]
