# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20171019_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='goods_invetory',
            field=models.IntegerField(default=0),
        ),
    ]
