# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_userbrowsehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('real_delete', models.BooleanField(default=False)),
                ('order_number', models.CharField(max_length=50)),
                ('order_addr', models.CharField(max_length=100)),
                ('order_recv', models.CharField(max_length=10)),
                ('order_fee', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('order_status', models.SmallIntegerField(choices=[(1, '待付费'), (2, '待发货'), (3, '待收货'), (4, '待完成')], default=1)),
                ('order_pay', models.SmallIntegerField(choices=[(1, '货到付款'), (2, '微信支付'), (3, '支付宝支付'), (4, '银联支付')], default=1)),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('real_delete', models.BooleanField(default=False)),
                ('detail_name', models.CharField(max_length=50)),
                ('detail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detail_amount', models.IntegerField()),
                ('detail_unit', models.CharField(max_length=20)),
                ('detail_img', models.ImageField(upload_to='goods')),
                ('detail_goodsid', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
